server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: ${ACTIVE_PROFILES:local}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revature-rms/rms-configuration-repo
          default-label: master
